### ISSUE TITLE
Either I'm trying to using it wrong on something is broken

### ISSUE THREAD

**Issue by majksner** [markets/sudo_rails#9]
Hi @markets,

Thanks for the gem! I'm trying to use it in my Rails app and it looks like it's not working. Let's say I would like to protect devise user edit method. In registrations_controller.rb

```ruby
class Users::RegistrationsController < Devise::RegistrationsController
  sudo only: [:edit]
end
```
as soon as I go to edit page it prompts sudo page with password 👍🏻. When I enter the password I just get redirected back to the same sudo page I can't reach edit page. That is one thing.

Another thing (or maybe it's not possible) is to protect `:update` method of a controller so when I click on a submit button to get the sudo page and after entering password to get form submitted.

**Comment by markets** [comment]
Hi @majksner, I'm actually using this gem in 3 Rails apps, in production, with zero problems, so not sure what's happening here... There is also tests covering this behaviour (https://github.com/markets/sudo_rails/blob/master/spec/controllers_spec.rb). 

I'd need a sample app to reproduce the error.

About your second question, since the gem performs a redirect after confirming the password:

https://github.com/markets/sudo_rails/blob/4392c04287d35a411491475aea6e152885359cf9/app/controllers/sudo_rails/application_controller.rb#L5-L11

Your `update` endpoint should accept GET requests too (https://stackoverflow.com/questions/985596/redirect-to-using-post-in-rails), but that's probably not ideal... Actually this gem is more focused on "protecting" actions/zones via GET (usually the page where you display the form, ala GitHub sudo).

**Comment by majksner** [comment]
Got it, thanks for looking into it. I had some issues with my browser resetting csrf tokens and that could make issues with your gem too because it resets session as well. I’ll check tomorrow. You can close the issue. Sorry for bothering you.

Best regards,
Nikola Majksner

________________________________

**Comment by markets** [comment]
> because it resets session as well

Ah yes! This can be problem since this gem relies on `session`. I'm going to close the issue, please reopen in case you found something :+1:
